### ISSUE TITLE
Right config but not work

### ISSUE THREAD

**Issue by Stetocasa** [BewhiskeredBard/homebridge-alexa-player#134]
### Description
Just copied and pasted the example config, using hoobs IP with a dummy port (5678)
Reported Italian domain (Amazon.it) 
But nothing appear in HomeKit and no info visible in the log 

![image](https://user-images.githubusercontent.com/70729310/107893577-46ae3c00-6f2c-11eb-8ea2-94099edfd4bf.jpeg)

**Comment by Stetocasa** [comment]
Log

15/2/2021, 01:27:52 [AlexaPlayer] Failed to initialize. Error: You can try to get the cookie manually by opening http://192.168.178.50:8000/ with your browser.
    at /home/hoobs/.hoobs/node_modules/alexa-cookie2/alexa-cookie.js:387:38
    at Server.<anonymous> (/home/hoobs/.hoobs/node_modules/alexa-cookie2/lib/proxy.js:366:30)
    at Object.onceWrapper (events.js:420:28)
    at Server.emit (events.js:314:20)
    at emitListeningNT (net.js:1351:10)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
15/2/2021, 01:27:52 Bridge is running on port 51826.

**Comment by Stetocasa** [comment]
Solved it with Hoobs support team 

Needs to login on Amazon typing host:port on broswer 
You can close it
