### ISSUE TITLE
Cannot get alexa cookie

### ISSUE THREAD

**Issue by unizhu** [BewhiskeredBard/homebridge-alexa-player#558]
Hello:
Use the latest homebridge and alexa player plugin

### Reproduction Steps
1. open auth URL on broswer
2. login to alexa
3. the page says : Amazon Alexa Cookie successfully retrieved. You can close the browser.

### Expected Behavior
the cookie can be received 

### Logs
Run Homebridge in debug mode (`homebridge --debug`) and include any Homebridge logs tagged with `[AlexaPlayer]`.

```
[homebridge-alexa-player] Failed to initialize. SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /var/lib/homebridge/node_modules/homebridge-alexa-player/node_modules/alexa-cookie2/alexa-cookie.js:532:67
    at IncomingMessage.<anonymous> (/var/lib/homebridge/node_modules/homebridge-alexa-player/node_modules/alexa-cookie2/alexa-cookie.js:111:33)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

### Screenshots
If applicable, add screenshots of the Home app or Alexa mobile app to help explain your problem.

### Additional Context

I use google chrome developer tools and see many set-cookie actions but is this useful?

**Comment by champagnearni** [comment]
> Hello: Use the latest homebridge and alexa player plugin
> 
> ### Description
> A clear and concise description of what the bug is.
> 
> ### Reproduction Steps
> Steps to reproduce the behavior:
> 
> 1. open auth URL on broswer
> 2. login to alexa
> 3. the page says : Amazon Alexa Cookie successfully retrieved. You can close the browser.
> 
> ### Expected Behavior
> the cookie can be received
> 
> ### Logs
> Run Homebridge in debug mode (`homebridge --debug`) and include any Homebridge logs tagged with `[AlexaPlayer]`.
> 
> ```
> [homebridge-alexa-player] Failed to initialize. SyntaxError: Unexpected end of JSON input
>     at JSON.parse (<anonymous>)
>     at /var/lib/homebridge/node_modules/homebridge-alexa-player/node_modules/alexa-cookie2/alexa-cookie.js:532:67
>     at IncomingMessage.<anonymous> (/var/lib/homebridge/node_modules/homebridge-alexa-player/node_modules/alexa-cookie2/alexa-cookie.js:111:33)
>     at IncomingMessage.emit (node:events:525:35)
>     at endReadableNT (node:internal/streams/readable:1358:12)
>     at processTicksAndRejections (node:internal/process/task_queues:83:21)
> ```
> 
> ### Screenshots
> If applicable, add screenshots of the Home app or Alexa mobile app to help explain your problem.
> 
> ### Additional Context
> I use google chrome developer tools and see many set-cookie actions but is this useful?

Getting the exact same issue, after following the same steps

**Comment by Karosieben** [comment]
Got the exact same issue.

Homebridge 1.8.5
homebridge-alexa-player-v0.5.3

Log:


```
[12/2/2024, 8:06:02 PM] [homebridge-alexa-player] Launched child bridge with PID 563860
[12/2/2024, 8:06:02 PM] [homebridge-alexa-player] Loaded homebridge-alexa-player v0.5.3 child bridge successfully
[12/2/2024, 8:06:02 PM] Loaded 0 cached accessories from cachedAccessories.0E6CDE1C352D.
[12/2/2024, 8:06:02 PM] [homebridge-alexa-player] Running homebridge-alexa-player-v0.5.3 with homebridge-v1.8.5 on node-v20.12.2.
[12/2/2024, 8:06:04 PM] [homebridge-alexa-player] Failed to initialize. Error: You can try to get the cookie manually by opening http://1.2.3.4:5678/ with your browser.
    at /var/lib/homebridge/node_modules/homebridge-alexa-player/node_modules/alexa-cookie2/alexa-cookie.js:387:38
    at Server.<anonymous> (/var/lib/homebridge/node_modules/homebridge-alexa-player/node_modules/alexa-cookie2/lib/proxy.js:368:30)
    at Object.onceWrapper (node:events:632:28)
    at Server.emit (node:events:530:35)
    at emitListeningNT (node:net:1931:10)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
[12/2/2024, 8:06:04 PM] Homebridge v1.8.5 (HAP v0.12.3) (homebridge-alexa-player) is running on port 41902.
[12/2/2024, 8:06:04 PM] 

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

[12/2/2024, 8:06:32 PM] [homebridge-alexa-player] Failed to initialize. SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /var/lib/homebridge/node_modules/homebridge-alexa-player/node_modules/alexa-cookie2/alexa-cookie.js:532:67
    at IncomingMessage.<anonymous> (/var/lib/homebridge/node_modules/homebridge-alexa-player/node_modules/alexa-cookie2/alexa-cookie.js:111:33)
    at IncomingMessage.emit (node:events:530:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

(IP Address masked)
