### ISSUE TITLE
Failed to Initialize

### ISSUE THREAD

**Issue by Doubledeucedavis** [BewhiskeredBard/homebridge-alexa-player#85]
I am attempting to set this up and I keep getting this error:
`Failed to initialize. Error: You can try to get the cookie manually by opening http://192.168.1.137::25858/ with your browser.
    at /usr/local/lib/node_modules/homebridge-alexa-player/node_modules/alexa-cookie2/alexa-cookie.js:387:38
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa-player/node_modules/alexa-cookie2/lib/proxy.js:366:30)
    at Object.onceWrapper (events.js:421:28)
    at Server.emit (events.js:315:20)
    at emitListeningNT (net.js:1352:10)
    at processTicksAndRejections (internal/process/task_queues.js:79:21)`

When I go to get the cookie, the page doesn't load and I get "Invalid Response"

I am in the US. I am not sure if I have the config setup correctly either.
`{
            "platform": "AlexaPlayer",
            "auth": {
                "proxy": {
                    "clientHost": "192.168.1.137:",
                    "port": 25858
                }
            },
            "screensAsTelevisions": true
        },`

**Comment by BewhiskeredBard** [comment]
Instead of `"192.168.1.137:"` in the config, use `"192.168.1.137"` (dropping the colon).

**Comment by Doubledeucedavis** [comment]
I did that and now I get this error
` Failed to initialize. Error: Error while checking Authentication: Error: Timeout
    at /usr/local/lib/node_modules/homebridge-alexa-player/node_modules/alexa-remote2/alexa-remote.js:153:49
    at /usr/local/lib/node_modules/homebridge-alexa-player/node_modules/alexa-remote2/alexa-remote.js:886:24
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa-player/node_modules/alexa-remote2/alexa-remote.js:858:17)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.emitRequestTimeout (_http_client.js:784:9)
    at Object.onceWrapper (events.js:421:28)
    at TLSSocket.emit (events.js:327:22)
    at TLSSocket.Socket._onTimeout (net.js:483:8)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)`

**Comment by Doubledeucedavis** [comment]
I did a complete reinstall on homebridge and now it works (mostly)
